### PR TITLE
[feature] AWS Elasticsearch Service support

### PR DESCRIPTION
**Pull request by rennokki**
First of all, I can say that the Elasticsearch ecosystem you built is great. I have tried to re-write it a while ago, [but I failed miserabily](https://github.com/renoki-co/elasticscout). All props to this. 

I have decided to take a part of it, like the [AWS Elasticsearch authentication through the client](https://github.com/renoki-co/elasticscout/blob/master/src/ElasticScoutServiceProvider.php#L87-L154), and merge it here.

The idea was initially forked from [cviebrock/laravel-elasticsearch](https://github.com/cviebrock/laravel-elasticsearch/blob/master/config/elasticsearch.php#L42-L58), then later merged in elastcscout, now it is here.

Not sure how to properly test this out. This was hard-tested on live AWS Elasticsearch Service.

### CODE REVIEW

**Comment by rennokki** [comment]
@babenkoivan I have to bump this.

**Comment by babenkoivan** [comment]
Hey @rennokki, nice job!

I'm afraid though, that this change might be breaking for some users. What if you extract this as a separate package and we describe the usage in README?

What I mean is that you can make a package with this specific handler and then configure it in `elastic.client.php`:

```php
return [
    'handler' => new CustomHandler([
         'host' => env('ELASTIC_HOST', '127.0.0.1'),
         'port' => env('ELASTIC_PORT', 9200),
         // ...
         'aws_enable' => env('ELASTIC_USE_AWS', false)
         // ...
    ])
];
```

I hope you got the idea 🙂

**Comment by rennokki** [comment]
@babenkoivan Sounds great. :D

**Comment by rennokki** [comment]
@babenkoivan After digging down a bit, the only issue here is that there are other dependants like [elastic-scout-driver](https://github.com/babenkoivan/elastic-scout-driver) and [elastic-migrations](https://github.com/babenkoivan/elastic-migrations) that might not benefit from this.

**Comment by rennokki** [comment]
@babenkoivan https://github.com/renoki-co/aws-elastic-client

**Comment by babenkoivan** [comment]
Hey @rennokki, it looks really good. I'm very busy lately, but I'll try to find some time and add a link to your handler in the project's README this week.

**Comment by babenkoivan** [comment]
@rennokki, I've just checked your package more closely and I think, that you shouldn't require `babenkoivan/elastic-client` in `composer.json`. It's better to install `babenkoivan/elastic-client` and then additionally your handler. Otherwise, it might be difficult to use AWS handler in `elastic-scout-driver` and other projects. Your handler should extend `elastic-client`, not replace it.

**Comment by rennokki** [comment]
@babenkoivan You're right, I should test it for the package in require-dev and eventually mark the package as being useful even for elasticsearch/elasticsearch

**Comment by rennokki** [comment]
@babenkoivan Perhaps you can document the implementation in this package as described in the section that is still available at [this commit](https://github.com/renoki-co/aws-elastic-client/tree/bc61a547ed95773113d745cfdd22d1258db08908#-usage). I'll change the use case with elasticsearch/elasticsearch directly.

**Comment by babenkoivan** [comment]
Hey, I've finally added AWS configuration section in the [README](https://github.com/babenkoivan/elastic-client#configuration) file 🙂

**Pull request closed without merging**
